service: ${env:SERVICE}
app: ${env:SERVICE}

plugins:
  - serverless-deployment-bucket

provider:
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  name: aws
  stage: ${env:STAGE}
  region: ${env:REGION}
  runtime: python3.7
  environment:
    REGION: ${env:REGION}
    STAGE: ${env:STAGE}

functions:
  cron:
    package:
      individually: true
      exclude:
        - venv/**
        - node_modules/**
        - .env
        - Makefile
        - package-lock.json
        - package.json
        - requirements.txt
        - README.md
    handler: src/cron.handle
    events:
    - schedule:
        name: crontab-test
        description: 'running scheduled cron on lambda'
        rate: cron(*/15 * * * ? *)
        enabled: true